- name: Deploy Calculator App Locally
  hosts: localhost
  vars:
    docker_image: "a3ryn/calculator-app:latest"
    container_name: "calculator-app"
  tasks:

    - name: Stop existing container (if running)
      community.docker.docker_container:
        name: "{{ container_name }}"
        state: stopped
      ignore_errors: yes

    - name: Remove old container
      community.docker.docker_container:
        name: "{{ container_name }}"
        state: absent
      ignore_errors: yes

    - name: Always pull latest image
      community.docker.docker_image:
        name: "{{ docker_image }}"
        source: pull

    - name: Start container interactively
      community.docker.docker_container:
        name: "{{ container_name }}"
        image: "{{ docker_image }}"
        state: started
        interactive: true
        tty: true
        restart_policy: no
